# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'quiz', '0001_initial'), (b'quiz', '0002_auto_20151225_1627'), (b'quiz', '0003_auto_20151225_1658')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('option_w', models.CharField(max_length=75)),
                ('option_x', models.CharField(max_length=75)),
                ('option_y', models.CharField(max_length=75)),
                ('option_z', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='subject',
            field=models.ManyToManyField(to=b'quiz.Subject'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('correctly_answered_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='correct_answer',
            field=models.CharField(default=None, max_length=75),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='option_w',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='option_x',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='option_y',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='option_z',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='questions_included',
            field=models.ManyToManyField(to=b'quiz.QuestionAnswer'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='subject',
            field=models.ManyToManyField(to=b'quiz.Subject'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='username',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='on',
            field=models.BooleanField(default=True),
        ),
    ]
