# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20151225_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='correct_answer',
            field=models.CharField(default=None, max_length=75),
        ),
    ]
