# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20151225_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question_text',
            field=models.TextField(max_length=150),
        ),
    ]
