# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20151225_1726'),
    ]

    operations = [
    ]
