# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20151225_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='option_w',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='option_x',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
