# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20151225_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.QuestionAnswer')),
                ('correct_answer', models.CharField(default=None, max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='questions_included',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='questions_included',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionAnswer'),
        ),
    ]
